[Network]
topology = MultiChipMesh
k_node = 4
chip_w = 5
chip_h = 5
buffer_size = 20
vc_number = 2
d2d_IF = off_chip_serial
# position_file = (using default sequential positions)

[Workload]
traffic = netrace

[Files]
netrace_file = input\netrace\trace_layer_359.tra.bz2
output_file = output/output.csv
log_file = output/log.txt
