# Test k_chip=6 without position_file
[Network]
topology = MultiChipMesh
k_node = 4
k_chip = 6
buffer_size = 20
vc_number = 2
d2d_IF = off_chip_serial

[Workload]
traffic = netrace

[Files]
netrace_file = input/netrace/sequential_test.tra.bz2
output_file = output/output_test_k6.csv
log_file = output/log_test_k6.txt
