# Test chip_w/chip_h format with 2x2 chiplets
[Network]
topology = MultiChipMesh
k_node = 2
chip_w = 2
chip_h = 2
buffer_size = 20
vc_number = 2
d2d_IF = off_chip_serial

[Workload]
traffic = netrace

[Files]
netrace_file = input/netrace/sequential_test.tra.bz2
output_file = output/output_test_wh.csv
log_file = output/log_test_wh.txt
